name: Unit test

on:
  pull_request:
    branches:
     - main
    paths:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Start server
      run: |
        node app.mjs &
        echo $! > server.pid
    - name: Test
      run: npm test
    - name: Stop server
      run: |
        kill $(cat server.pid)
        rm server.pid